# Generated by Django 3.2.4 on 2021-06-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_chaptersindexpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='description',
            new_name='introduction',
        ),
    ]
