# Generated by Django 3.2.6 on 2021-10-28 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0004_rename_description_chapter_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
