# Generated by Django 3.2.6 on 2021-11-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_chapter_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='social_media',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
