# Generated by Django 3.2.6 on 2021-11-16 04:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_chapter_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='social_media',
        ),
        migrations.AddField(
            model_name='chapter',
            name='links',
            field=wagtail.core.fields.StreamField([('social_media_link', wagtail.core.blocks.URLBlock(form_classname='social media link', required=False)), ('website_link', wagtail.core.blocks.URLBlock(form_classname='website link', required=False))], blank=True),
        ),
    ]
