# Generated by Django 3.2.6 on 2021-12-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangout',
            name='url',
        ),
    ]
