# Generated by Django 3.2.6 on 2021-12-06 08:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0002_remove_hangout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='url',
            field=wagtail.core.fields.StreamField([('hangout_link', wagtail.core.blocks.URLBlock(form_classname='hangout link', required=False))], blank=True),
        ),
    ]
