# Generated by Django 3.2.4 on 2021-06-20 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0004_rename_description_chapter_introduction'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'chapter')},
        ),
    ]
