# Generated by Django 3.2.6 on 2021-09-23 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0003_auto_20210816_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendInvitation',
        ),
        migrations.DeleteModel(
            name='InviteFriendsPage',
        ),
    ]
